@startuml conceptualClassDiagram

left to right direction

package "Usuarios y valoraciones" {
  class Usuario {
    - nombre
    - apellidos
    - correo electrónico
    - contraseña
    - foto
    - rol
  }

  class Valoracion {
    - estrellas
    - fecha publicación
    - descripción
  }

  Usuario "1" <-- "*" Valoracion : realiza >
}

package "Compras" {
  class Compra {
    - fecha de compra
  }

  class LineaCompra {
    - fecha válida
    - cantidad
    - coste total
  }

  Usuario "1" <-- "*" Compra : realiza >
  Compra "1" <-- "*" LineaCompra : contiene >
}

package "Entradas y descuentos" {
  class TipoEntrada {
    - nombre
    - descripción
    - precio
    - moneda
    - máximo por día
  }

  class Descuento {
    - porcentaje
    - fecha expiración
    - código
  }

  LineaCompra "*" --> "1" TipoEntrada : pertenece a >
  Descuento "*" -- "*" TipoEntrada : aplica a >
}

package "Otros" {
  class Atraccion {
    - nombre
    - intensidad
    - edad mínima
    - altura mínima
    - peso mínimo
    - descripción
    - foto
    - activa
  }

  class TokenRecuperacion {
    - token
    - fecha expiración
  }

  Usuario "1" --> "*" TokenRecuperacion : genera >
}

enum Rol {
  ADMIN
  USUARIO
}

enum Intensidad {
  BAJA
  MEDIA
  ALTA
}

Usuario --> Rol
Atraccion --> Intensidad

@enduml
