@startuml detailedClassDiagram

left to right direction

package "Usuarios y valoraciones" {
  class User {
    String username {required, unique, maxLength=50}
    String firstname {required, maxLength=50}
    String lastname {required, maxLength=50}
    String email {required, unique, emailFormat}
    String password {required, minLength=8, maxLength=100, mustContain="upper,lower,number,special"}
    String photoUrl {optional}
    Role role {required, values={ADMIN,USER}}
  }
  interface UserDetails {
    Collection<GrantedAuthority> getAuthorities()
    String getPassword()
    String getUsername()
    boolean isAccountNonExpired()
    boolean isAccountNonLocked()
    boolean isCredentialsNonExpired()
    boolean isEnabled()
  }
  class Review  {
    Double stars {required, range=0..5}
    LocalDate publicationDate {required}
    String description {required, maxLength=255}
    User user {required}
  }
  class BaseEntity {
    Long id
  }
  User --|> BaseEntity
  User ..|> UserDetails
  User --> Role
  Review --|> BaseEntity
  User "1" <-- "*" Review
}

package "Compras" {
  class Purchase {
    LocalDate purchaseDate {required}
    User buyer {required}
  }
  class PurchaseLine {
    LocalDate validDate {required}
    Integer quantity {required, positive}
    Purchase purchase {required}
    BigDecimal totalCost {required, positive}
    String ticketTypeName {required}
  }
  Purchase "1" <-- "*" PurchaseLine
  User "1" <-- "*" Purchase
}

package "Entradas y Descuentos" {
  class TicketType {
    BigDecimal cost {required, positive}
    String currency
    String typeName {required, maxLength=50}
    String description {required, maxLength=255}
    Integer maxPerDay {required, positive}
  }
  class Discount {
    Integer discountPercentage {required, positive, max=100}
    LocalDate expiryDate {required}
    String discountCode {required, maxLength=20}
    TicketType ticketType {required}
  }
  TicketType --|> BaseEntity
  Discount --|> BaseEntity
  Discount "*" -- "*" TicketType
}

package "Otros" {
  class Attraction {
    String name {required, maxLength=50}
    Intensity intensity {required, values={LOW,MEDIUM,HIGH}}
    Integer minimumHeight {required, min=0}
    Integer minimumAge {required, min=0}
    Integer minimumWeight {required, min=0}
    String description {required, maxLength=255}
    String photoUrl {required}
    Boolean isActive {required}
  }
  class PasswordResetToken {
    String token {required}
    LocalDateTime expiryDate {required}
    User user {required}
  }
  Attraction --|> BaseEntity
  Attraction --> Intensity
  PasswordResetToken --|> BaseEntity
  PasswordResetToken "*" --> "1" User
}

enum Role {
  USER
  ADMIN
}

enum Intensity {
  LOW
  MEDIUM
  HIGH
}

note right of Review
REGN-001: Un usuario no podrá dejar una valoración sin haber comprado
y utilizado una entrada válida del parque.
end note

note bottom of PurchaseLine
REGN-002: La fecha de validez de una línea de compra debe ser igual o posterior
a la fecha actual y para la que queden entradas disponibles (no se permiten entradas para fechas pasadas o de lleno).
end note

note bottom of TicketType
REGN-003: No se podrán vender más entradas de un tipo por día
que el máximo definido en "maxPerDay".
end note

note left of Review::description
REGN-005: La descripción de una valoración no puede contener palabras ofensivas
o inapropiadas.
end note

@enduml
